-- MySQL Script generated by MySQL Workbench
-- Tue Mar 11 19:34:30 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agromx_20250311` DEFAULT CHARACTER SET utf8 ;
USE `agromx_20250311` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agromx_20250311`.`Users` (
  `user_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(50) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agromx_20250311`.`Categories` (
  `category_id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(300) NOT NULL,
  `url_image` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agromx_20250311`.`Producers` (
  `producer_id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`producer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agromx_20250311`.`Products` (
  `product_id` BIGINT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `unit` VARCHAR(10) NOT NULL,
  `stock` BIGINT NOT NULL,
  `fk_category_id` BIGINT NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `benefits` VARCHAR(1000) NOT NULL,
  `fk_producer_id` BIGINT NOT NULL,
  PRIMARY KEY (`product_id`, `fk_category_id`, `fk_producer_id`),
  INDEX `fk_Products_Categories_idx` (`fk_category_id` ASC) VISIBLE,
  INDEX `fk_Products_Producers1_idx` (`fk_producer_id` ASC) VISIBLE,
  CONSTRAINT `fk_Products_Categories`
    FOREIGN KEY (`fk_category_id`)
    REFERENCES `agromx_20250311`.`Categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_Producers1`
    FOREIGN KEY (`fk_producer_id`)
    REFERENCES `agromx_20250311`.`Producers` (`producer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Techniques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agromx_20250311`.`Techniques` (
  `technique_id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`technique_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agromx_20250311`.`Orders` (
  `order_id` BIGINT NOT NULL AUTO_INCREMENT,
  `date_time` DATETIME NOT NULL,
  `fk_user_id` BIGINT NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`order_id`, `fk_user_id`),
  INDEX `fk_Sales_Users1_idx` (`fk_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Sales_Users1`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `agromx_20250311`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agromx_20250311`.`Product_Order` (
  `fk_order_id` BIGINT NOT NULL,
  `fk_product_id` BIGINT NOT NULL,
  `amount_sold` DECIMAL(10,2) NOT NULL,
  `quanty` BIGINT NOT NULL,
  PRIMARY KEY (`fk_order_id`, `fk_product_id`),
  INDEX `fk_Products_has_order_order1_idx` (`fk_order_id` ASC) VISIBLE,
  INDEX `fk_product_order_Products1_idx` (`fk_product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Products_has_order_order1`
    FOREIGN KEY (`fk_order_id`)
    REFERENCES `agromx_20250311`.`Orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_order_Products1`
    FOREIGN KEY (`fk_product_id`)
    REFERENCES `agromx_20250311`.`Products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producers_has_Techniques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agromx_20250311`.`Producers_has_Techniques` (
  `fk_producer_id` BIGINT NOT NULL,
  `fk_technique_id` BIGINT NOT NULL,
  PRIMARY KEY (`fk_producer_id`, `fk_technique_id`),
  INDEX `fk_Producers_has_Tecniques_Producers1_idx` (`fk_producer_id` ASC) VISIBLE,
  INDEX `fk_Producers_has_Tecniques_Tecniques1_idx` (`fk_technique_id` ASC) VISIBLE,
  CONSTRAINT `fk_Producers_has_Techniques_Producers1`
    FOREIGN KEY (`fk_producer_id`)
    REFERENCES `agromx_20250311`.`Producers` (`producer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producers_has_Tecniques_Techniques1`
    FOREIGN KEY (`fk_technique_id`)
    REFERENCES `agromx_20250311`.`Techniques` (`technique_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`privileges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agromx_20250311`.`Privileges` (
  `privilege_id` BIGINT NOT NULL AUTO_INCREMENT,
  `privilege_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`privilege_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_privilege`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agromx_20250311`.`user_has_privilege` (
  `fk_privilege_id` BIGINT NOT NULL,
  `fk_user_id` BIGINT NOT NULL,
  PRIMARY KEY (`fk_privilege_id`, `fk_user_id`),
  INDEX `fk_user_has_privilege_privileges1_idx` (`fk_privilege_id` ASC) VISIBLE,
  INDEX `fk_user_has_privilege_Users1_idx` (`fk_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_privilege_privileges1`
    FOREIGN KEY (`fk_privilege_id`)
    REFERENCES `agromx_20250311`.`privileges` (`privilege_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_privilege_Users1`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `agromx_20250311`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
